appname := TallyPiazzaPollResults
.PHONY: TallyPiazzaPollResults

CXX := g++
CXXFLAGS := -Wall -g

srcfiles := TallyPiazzaPollResults.cpp

all: $(appname)

$(appname):
	@$(CXX) $(CXXFLAGS) $(srcfiles) -o ../TallyPiazzaPollResults

clean:
	rm -f ../TallyPiazzaPollResults

